### PR TITLE
Adding Ministry of Testing Courses

### PR DESCRIPTION
**Pull request by FriendlyTester**
Hello Unmesh, a PR containing the MoT courses :)

### CODE REVIEW

**Comment by upgundecha** [comment]
Hi Richard, thanks a lot for adding MoS to the list. 

Can you please also help arrange the entry for MoS in alphabetical order? Makes it easier to follow through when anyone looks at the list.

**Review by upgundecha — CHANGES_REQUESTED** [review]
Hi Richard, Can you please also help arrange the entry for MoS in alphabetical order? This will make it easier to follow through when anyone looks at the list.

Can we also add tutorials from https://automationintesting.com/onlinecourses/index.html?

Thanks,
Unmesh

**Comment by FriendlyTester** [comment]
Hey @upgundecha I think that should do the trick.
Made the whole MoT entry alphabetical with the rest, and then each section alphabetical within MoT's section.

I also added the automation in testing courses.

**Comment by upgundecha** [comment]
Brilliant, thank you @FriendlyTester!

**Pull request merged**
