### PR TITLE
Adding new Expertly courses

### PR DESCRIPTION
**Pull request by rahulkiwiqa**
https://expertley.com/

### CODE REVIEW

**Review by upgundecha — CHANGES_REQUESTED** [review]
Hello Rahul, thanks for your contribution

Please remove courses related to certifications. I would like to keep this list focused on core skills.

Thanks,
Unmesh

**Comment by rahulkiwiqa** [comment]
Hi Unmesh, I removed certification courses as you suggested.
Can you please review it again.

**Comment by upgundecha** [comment]
Hello @rahulkiwiqa it's difficult to find out the course content on your website. Honestly, I don't want this to be a marketing page. The course fees are very expensive, in fact, a single course costs way more than entire year of Pluralsight or LinkedIn learning subscription.  I'm not accepting the listings where I cannot verify the content quality. Sorry mate.

**Comment by rahulkiwiqa** [comment]
Hi @upgundecha - clicking on each course, you will find all the descriptions in details about course quality and content.
For example - https://expertley.com/collections/quick-self-paced-classes/products/automation-programming-concepts, You'll find course content in Description section.

**Pull request closed without merging**
